# This is a basic workflow to help you get started with Actions

name: DockerPush

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uperformkarthick/sample-github-actions:latest, uperformkarthick/sample-github-actions:${{ steps.vars.outputs.sha_short }}

      - name: Run docker 
        run: docker run uperformkarthick/sample-github-actions:${{ steps.vars.outputs.sha_short }}
          
